# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Sun Aug 10 21:46:08 2014
#

import wx
# begin wxGlade: dependencies
import wx.calendar
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

from MyFrame import *


class crear_oferta(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: crear_oferta.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.calendar_ctrl_4 = wx.calendar.CalendarCtrl(self, wx.ID_ANY, style=wx.calendar.CAL_MONDAY_FIRST)
        self.text_ctrl_10 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.sizer_35_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Nombre"))
        self.text_ctrl_5 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.sizer_26_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Duracion"))
        self.text_ctrl_6 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.sizer_27_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Precio"))
        self.checkbox_3 = wx.CheckBox(self, wx.ID_ANY, "")
        self.sizer_28_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Activo"))
        self.button_15 = wx.Button(self, wx.ID_ANY, _("img"))
        self.button_16 = wx.Button(self, wx.ID_ANY, _("Guardar"))
        self.list_ctrl_5 = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.sizer_29_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Items"))
        self.button_17 = wx.Button(self, wx.ID_ANY, _("<<"))
        self.button_18 = wx.Button(self, wx.ID_ANY, _(">>"))
        self.list_ctrl_4 = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_REPORT | wx.SUNKEN_BORDER)

        self.list_ctrl_4.InsertColumn(0,"Nombre")
        self.list_ctrl_4.InsertColumn(1,"Disponible")

        self.list_ctrl_5.InsertColumn(0,"Nombre")
        self.list_ctrl_5.InsertColumn(1,"Disponible")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT, self.solo_num, self.text_ctrl_5)
        self.Bind(wx.EVT_TEXT, self.solo_num, self.text_ctrl_6)
        self.Bind(wx.EVT_CHECKBOX, self.activo, self.checkbox_3)
        self.Bind(wx.EVT_BUTTON, self.load_img_oferta, self.button_15)
        self.Bind(wx.EVT_BUTTON, self.guardar_oferta, self.button_16)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.item_selec2, self.list_ctrl_5)
        self.Bind(wx.EVT_BUTTON, self.pasar_izq, self.button_17)
        self.Bind(wx.EVT_BUTTON, self.pasar_der, self.button_18)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.item_select, self.list_ctrl_4)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: crear_oferta.__set_properties
        self.SetTitle(_("frame_2"))
        self.SetSize((648, 529))
        self.checkbox_3.SetValue(1)
        self.list_ctrl_5.SetMinSize((160, 469))
        self.list_ctrl_4.SetMinSize((164, 500))
        self.calendar_ctrl_4.SetMinSize((215, 140))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: crear_oferta.__do_layout
        sizer_24 = wx.BoxSizer(wx.VERTICAL)
        sizer_25 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_10 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_30 = wx.BoxSizer(wx.VERTICAL)
        sizer_31 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_29_staticbox.Lower()
        sizer_29 = wx.StaticBoxSizer(self.sizer_29_staticbox, wx.HORIZONTAL)
        grid_sizer_9 = wx.FlexGridSizer(7, 1, 0, 0)
        self.sizer_28_staticbox.Lower()
        sizer_28 = wx.StaticBoxSizer(self.sizer_28_staticbox, wx.HORIZONTAL)
        self.sizer_27_staticbox.Lower()
        sizer_27 = wx.StaticBoxSizer(self.sizer_27_staticbox, wx.HORIZONTAL)
        self.sizer_26_staticbox.Lower()
        sizer_26 = wx.StaticBoxSizer(self.sizer_26_staticbox, wx.HORIZONTAL)
        self.sizer_35_staticbox.Lower()
        sizer_35 = wx.StaticBoxSizer(self.sizer_35_staticbox, wx.HORIZONTAL)
        grid_sizer_9.Add(self.calendar_ctrl_4, 0, 0, 0)
        sizer_35.Add(self.text_ctrl_10, 0, 0, 0)
        grid_sizer_9.Add(sizer_35, 1, wx.EXPAND, 0)
        sizer_26.Add(self.text_ctrl_5, 0, 0, 0)
        grid_sizer_9.Add(sizer_26, 1, wx.EXPAND, 0)
        sizer_27.Add(self.text_ctrl_6, 0, 0, 0)
        grid_sizer_9.Add(sizer_27, 1, wx.EXPAND, 0)
        sizer_28.Add(self.checkbox_3, 0, 0, 0)
        grid_sizer_9.Add(sizer_28, 1, wx.EXPAND, 0)
        grid_sizer_9.Add(self.button_15, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_9.Add(self.button_16, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_25.Add(grid_sizer_9, 1, wx.EXPAND, 0)
        sizer_29.Add(self.list_ctrl_5, 1, wx.EXPAND, 0)
        sizer_25.Add(sizer_29, 1, wx.EXPAND, 0)
        sizer_30.Add((80, 200), 0, 0, 0)
        sizer_31.Add(self.button_17, 0, 0, 0)
        sizer_31.Add(self.button_18, 0, 0, 0)
        sizer_30.Add(sizer_31, 1, wx.EXPAND, 0)
        grid_sizer_10.Add(sizer_30, 1, wx.EXPAND, 0)
        grid_sizer_10.Add(self.list_ctrl_4, 1, wx.EXPAND, 0)
        sizer_25.Add(grid_sizer_10, 1, wx.EXPAND, 0)
        sizer_24.Add(sizer_25, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_24)
        self.Layout()
        # end wxGlade

    def solo_num(self, event):  # wxGlade: crear_oferta.<event_handler>
        print "Event handler 'solo_num' not implemented!"
        event.Skip()

    def activo(self, event):  # wxGlade: crear_oferta.<event_handler>
        print "Event handler 'activo' not implemented!"
        event.Skip()

    def load_img_oferta(self, event):  # wxGlade: crear_oferta.<event_handler>
        print "Event handler 'load_img_oferta' not implemented!"
        event.Skip()

    def guardar_oferta(self, event):  # wxGlade: crear_oferta.<event_handler>
        print "Event handler 'guardar_oferta' not implemented!"
        event.Skip()

    def item_selec2(self, event):  # wxGlade: crear_oferta.<event_handler>
        print "Event handler 'item_selec2' not implemented!"
        event.Skip()

    def pasar_izq(self, event):  # wxGlade: crear_oferta.<event_handler>
        print "Event handler 'pasar_izq' not implemented!"
        event.Skip()

    def pasar_der(self, event):  # wxGlade: crear_oferta.<event_handler>
        print "Event handler 'pasar_der' not implemented!"
        event.Skip()

    def item_select(self, event):  # wxGlade: crear_oferta.<event_handler>
        print "Event handler 'item_select' not implemented!"
        event.Skip()

# end of class crear_oferta
