# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Sun Aug 10 21:46:08 2014
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

from MyFrame import *

class crear_item(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: crear_item.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.text_ctrl_8 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.sizer_32_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Nombre"))
        self.text_ctrl_9 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.sizer_33_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Precio"))
        self.combo_box_1 = wx.ComboBox(self, wx.ID_ANY, choices=[_("Primero"), _("Segundo"), _("Postre")], style=wx.CB_DROPDOWN)
        self.sizer_20_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Tipo"))
        self.text_ctrl_4 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.sizer_21_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Descripcion"))
        self.button_13 = wx.Button(self, wx.ID_ANY, _("img"))
        self.sizer_22_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Imagen"))
        self.checkbox_2 = wx.CheckBox(self, wx.ID_ANY, "")
        self.sizer_23_staticbox = wx.StaticBox(self, wx.ID_ANY, _("Disponible"))
        self.button_12 = wx.Button(self, wx.ID_ANY, _("Crear"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT, self.solo_num, self.text_ctrl_9)
        self.Bind(wx.EVT_BUTTON, self.load_img_item, self.button_13)
        self.Bind(wx.EVT_CHECKBOX, self.item_disp, self.checkbox_2)
        self.Bind(wx.EVT_BUTTON, self.crear_item_go, self.button_12)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: crear_item.__set_properties
        self.SetTitle(_("frame_1"))
        self.combo_box_1.SetSelection(-1)
        self.text_ctrl_4.SetMinSize((200, 100))
        self.checkbox_2.SetValue(1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: crear_item.__do_layout
        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_8 = wx.GridSizer(2, 3, 0, 0)
        self.sizer_23_staticbox.Lower()
        sizer_23 = wx.StaticBoxSizer(self.sizer_23_staticbox, wx.HORIZONTAL)
        self.sizer_22_staticbox.Lower()
        sizer_22 = wx.StaticBoxSizer(self.sizer_22_staticbox, wx.HORIZONTAL)
        self.sizer_21_staticbox.Lower()
        sizer_21 = wx.StaticBoxSizer(self.sizer_21_staticbox, wx.HORIZONTAL)
        self.sizer_20_staticbox.Lower()
        sizer_20 = wx.StaticBoxSizer(self.sizer_20_staticbox, wx.HORIZONTAL)
        sizer_19 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_33_staticbox.Lower()
        sizer_33 = wx.StaticBoxSizer(self.sizer_33_staticbox, wx.HORIZONTAL)
        self.sizer_32_staticbox.Lower()
        sizer_32 = wx.StaticBoxSizer(self.sizer_32_staticbox, wx.HORIZONTAL)
        sizer_32.Add(self.text_ctrl_8, 0, wx.EXPAND, 0)
        sizer_19.Add(sizer_32, 1, wx.EXPAND, 0)
        sizer_33.Add(self.text_ctrl_9, 0, wx.EXPAND, 0)
        sizer_19.Add(sizer_33, 1, wx.EXPAND, 0)
        grid_sizer_8.Add(sizer_19, 1, wx.EXPAND, 0)
        sizer_20.Add(self.combo_box_1, 0, 0, 0)
        grid_sizer_8.Add(sizer_20, 1, wx.EXPAND, 0)
        sizer_21.Add(self.text_ctrl_4, 0, wx.EXPAND, 0)
        grid_sizer_8.Add(sizer_21, 1, wx.EXPAND, 0)
        sizer_22.Add(self.button_13, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_8.Add(sizer_22, 1, wx.EXPAND, 0)
        sizer_23.Add(self.checkbox_2, 0, 0, 0)
        grid_sizer_8.Add(sizer_23, 1, wx.EXPAND, 0)
        grid_sizer_8.Add(self.button_12, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL | wx.SHAPED, 0)
        sizer_18.Add(grid_sizer_8, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_18)
        sizer_18.Fit(self)
        self.Layout()
        # end wxGlade

    def solo_num(self, event):  # wxGlade: crear_item.<event_handler>
        print "Event handler 'solo_num' not implemented!"
        event.Skip()

    def load_img_item(self, event):  # wxGlade: crear_item.<event_handler>
        print "Event handler 'load_img_item' not implemented!"
        event.Skip()

    def item_disp(self, event):  # wxGlade: crear_item.<event_handler>
        print "Event handler 'item_disp' not implemented!"
        event.Skip()

    def crear_item_go(self, event):  # wxGlade: crear_item.<event_handler>
        print "Event handler 'crear_item_go' not implemented!"
        event.Skip()

# end of class crear_item
